server:
  port: 8080


spring:
  application:
    name: gateway
  main:
    lazy-initialization: true
    
#  cloud:
#    gateway:
#      routes:
#      - id: serviceAbc
##        uri: http://localhost:8070/
#        uri: lb://eureka-service-abc/
#        predicates:
#        - Path=/serviceAbc/**
#        filters:
#        - RewritePath=/serviceAbc(?<path>/?.*), $\{path}     # /serviceAbc/greetings, this sets the path to /greetings before making the downstream request
#        - AddRequestHeader=first-request, first-request-header
#        - AddResponseHeader=first-response, first-response-header
#      - id: serviceDef
#        uri: lb://EUREKA-SERVICE-DEF/ #http://localhost:8071/
#        predicates:
#        - Path=/serviceDef/**
#        filters:
#        - RewritePath=/serviceDef(?<path>/?.*), $\{path}     # /serviceDef/greetings, this sets the path to /greetings before making the downstream request
##        - RewritePath=/serviceDef, /backingServiceEndpoint
##        - RewritePath=/red(?<path>/?.*), $\{path}     # /serviceDef/red/blue, this sets the path to /serviceDef/blue before making the downstream request
##      discovery:
##        locator:
##          lower-case-service-id: true
##          enabled: true

eureka:
  instance:
#    hostname: ${APPLICATION_DOMAIN}    # Not needed if you are running on a machine that knows its own hostname 
#    nonSecurePort: 80  
    preferIpAddress: true              # When the application registers with eureka, it uses its IP address rather than its hostname.
    lease-renewal-interval-in-seconds: 10   # DO NOT DO THIS IN PRODUCTION
    metadata-map:
      customProp: customPropValue
      name: ${spring.application.name}
      type: gateway
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
#      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}



#debug: false

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG