spring:
  application:
    name: spring-cloud-eureka-feign-client
  main:
    lazy-initialization: true    
server:
  port: 8090

eureka:
  instance:
    lease-renewal-interval-in-seconds: 10   # DO NOT DO THIS IN PRODUCTION
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
      
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic