
server:
  port: 8888

spring:
    application:
        name: config-server
    main:
        lazy-initialization: true
                
    profiles:
        active:
        - native

management:
    endpoints:
        web:
            exposure:
                include: '*'
