
server:
  port: 8888

spring:
    application:
        name: config-server
    main:
        lazy-initialization: true
                
    profiles:
        active:
        - native
        
#    cloud:                 # if not the native profile, give the folder explicitly as-
#      config:
#        server:
#          native:
#            search-locations:
#            - /common-config

management:
    endpoints:
        web:
            exposure:
                include: '*'
